services:
  housing-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"

  housing-streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://housing-api:8000/predict
    depends_on:
      - housing-api
